# Site settings
title: Tobago
client:
  name: Tobago Tourism Agency
  link: https://www.visittobago.gov.tt/
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Tobago’s small size belies the weighty punch it delivers to those looking for an authentic island paradise. Covered in unspoilt rainforests, fringed by exquisite beaches, and offering an island saunter that is truly intoxicating, Tobago is an untouched Caribbean idyll. Known as the laid-back, undiscovered neighbour to Trinidad, you’ll find enchanting outdoor adventures, exquisite diving and snorkelling, and the chilled hubbub of the rum shack hangouts. Warm welcomes and Caribbean charm by the bucket load await on Tobago.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/tobago" # the subpath of your site, e.g. /blog/
img:     "/tobago/_assets/img"
css:     "/tobago/_assets/css"
js:      "/tobago/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed